name: extended_image
description: Official extension image, support placeholder(loading)/ failed state, cache network, zoom/pan, photo view, slide out page, editor(crop,rotate,flip), painting etc.
version: 9.0.4
repository: https://github.com/fluttercandies/extended_image
issue_tracker: https://github.com/fluttercandies/extended_image/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  extended_image_library:
    git:
      url: https://github.com/LeeeYudE/extended_image_library.git
      ref: 3382bffc5cfa3e9b9a81b58850211f6733503180
  flutter:
    sdk: flutter
  meta: ^1.7.0
  vector_math: ^2.1.4
dependency_overrides:
  # extended_image_library:
  #   path: ../extended_image_library

